repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.7.4
    hooks:
      - id: uv-lock
  - repo: local
    hooks:
      - id: ruff format
        name: ruff format
        entry: ruff format --check --diff
        language: system
        types: [python]
      - id: ruff check
        name: ruff check
        entry: ruff check .
        language: system
        types: [python]
