name: Format and Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          source ~/.cargo/env
          uv pip install -e .[dev] --system
      - name: Lint with ruff
        run: |
          source ~/.cargo/env
          ruff check .
      - name: Format with ruff
        run: |
          source ~/.cargo/env
          ruff format .
