name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install en_US.UTF-8 locale
        run: |
          sudo locale-gen en_US.UTF-8
          sudo update-locale LANG=en_US.UTF-8
      - name: install ffmpeg dependency
        run: |
          sudo apt-get update
          sudo apt-get install --yes --no-install-recommends \
            ffmpeg
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Install dependencies
        run: uv sync --locked --all-extras --dev
      - name: Run unit tests
        run: uv run pytest tests/
